# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "datashift"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thomas Statter"]
  s.date = "2012-02-05"
  s.description = "A suite of tools to move data between ActiveRecord models,databases,applications like Excel/Open Office, files and projects including Spree"
  s.email = "rubygems@autotelik.co.uk"
  s.executables = ["autospec", "convert_to_should_syntax", "erubis", "htmldiff", "jeweler", "ldiff", "nokogiri", "rackup", "rails", "rake", "rake2thor", "ri", "rspec", "spree", "thor", "tilt", "tt"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.markdown",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.markdown",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/autospec",
    "bin/convert_to_should_syntax",
    "bin/erubis",
    "bin/htmldiff",
    "bin/jeweler",
    "bin/ldiff",
    "bin/nokogiri",
    "bin/rackup",
    "bin/rails",
    "bin/rake",
    "bin/rake2thor",
    "bin/ri",
    "bin/rspec",
    "bin/spree",
    "bin/thor",
    "bin/tilt",
    "bin/tt",
    "datashift-0.0.1.gem",
    "datashift.gemspec",
    "lib/applications/jruby/jexcel_file.rb",
    "lib/applications/jruby/word.rb",
    "lib/datashift.rb",
    "lib/datashift/exceptions.rb",
    "lib/datashift/file_definitions.rb",
    "lib/datashift/mapping_file_definitions.rb",
    "lib/datashift/method_detail.rb",
    "lib/datashift/method_mapper.rb",
    "lib/generators/csv_generator.rb",
    "lib/generators/excel_generator.rb",
    "lib/generators/generator_base.rb",
    "lib/helpers/core_ext/to_b.rb",
    "lib/helpers/spree_helper.rb",
    "lib/java/poi-3.7/._poi-3.7-20101029.jar5645100390082102460.tmp",
    "lib/java/poi-3.7/LICENSE",
    "lib/java/poi-3.7/NOTICE",
    "lib/java/poi-3.7/RELEASE_NOTES.txt",
    "lib/java/poi-3.7/lib/commons-logging-1.1.jar",
    "lib/java/poi-3.7/lib/junit-3.8.1.jar",
    "lib/java/poi-3.7/lib/log4j-1.2.13.jar",
    "lib/java/poi-3.7/ooxml-lib/dom4j-1.6.1.jar",
    "lib/java/poi-3.7/ooxml-lib/geronimo-stax-api_1.0_spec-1.0.jar",
    "lib/java/poi-3.7/ooxml-lib/xmlbeans-2.3.0.jar",
    "lib/java/poi-3.7/poi-3.7-20101029.jar",
    "lib/java/poi-3.7/poi-examples-3.7-20101029.jar",
    "lib/java/poi-3.7/poi-ooxml-3.7-20101029.jar",
    "lib/java/poi-3.7/poi-ooxml-schemas-3.7-20101029.jar",
    "lib/java/poi-3.7/poi-scratchpad-3.7-20101029.jar",
    "lib/loaders/csv_loader.rb",
    "lib/loaders/excel_loader.rb",
    "lib/loaders/loader_base.rb",
    "lib/loaders/spreadsheet_loader.rb",
    "lib/loaders/spree/image_loader.rb",
    "lib/loaders/spree/product_loader.rb",
    "spec/csv_loader_spec.rb",
    "spec/datashift_spec.rb",
    "spec/db/migrate/20110803201325_create_test_bed.rb",
    "spec/excel_generator_spec.rb",
    "spec/excel_loader_spec.rb",
    "spec/file_definitions.rb",
    "spec/fixtures/BadAssociationName.xls",
    "spec/fixtures/DemoNegativeTesting.xls",
    "spec/fixtures/ProjectsMultiCategories.xls",
    "spec/fixtures/ProjectsSingleCategories.xls",
    "spec/fixtures/SimpleProjects.xls",
    "spec/fixtures/config/database.yml",
    "spec/fixtures/interact_models_db.sqlite",
    "spec/fixtures/interact_spree_db.sqlite",
    "spec/fixtures/negative/SpreeProdMiss1Mandatory.csv",
    "spec/fixtures/negative/SpreeProdMiss1Mandatory.xls",
    "spec/fixtures/negative/SpreeProdMissManyMandatory.csv",
    "spec/fixtures/negative/SpreeProdMissManyMandatory.xls",
    "spec/fixtures/simple_export_spec.xls",
    "spec/fixtures/simple_template_spec.xls",
    "spec/fixtures/spree/SpreeProducts.csv",
    "spec/fixtures/spree/SpreeProducts.xls",
    "spec/fixtures/spree/SpreeProductsMultiColumn.csv",
    "spec/fixtures/spree/SpreeProductsMultiColumn.xls",
    "spec/fixtures/spree/SpreeProductsSimple.csv",
    "spec/fixtures/spree/SpreeProductsSimple.xls",
    "spec/fixtures/spree/SpreeZoneExample.csv",
    "spec/fixtures/spree/SpreeZoneExample.xls",
    "spec/fixtures/test_model_defs.rb",
    "spec/loader_spec.rb",
    "spec/method_mapper_spec.rb",
    "spec/spec_helper.rb",
    "spec/spree_generator_spec.rb",
    "spec/spree_loader_spec.rb",
    "spec/spree_method_mapping_spec.rb",
    "tasks/config/seed_fu_product_template.erb",
    "tasks/config/tidy_config.txt",
    "tasks/db_tasks.rake",
    "tasks/excel_generator.rake",
    "tasks/file_tasks.rake",
    "tasks/import/csv.rake",
    "tasks/import/excel.rake",
    "tasks/spree/image_load.rake",
    "tasks/spree/product_loader.rake",
    "tasks/word_to_seedfu.rake",
    "test/helper.rb",
    "test/test_interact.rb"
  ]
  s.homepage = "http://github.com/autotelik/datashift"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Shift data betwen applications and Active Record"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rails>, ["= 3.1.3"])
      s.add_development_dependency(%q<activerecord>, ["= 3.1.3"])
      s.add_development_dependency(%q<activesupport>, ["= 3.1.3"])
      s.add_development_dependency(%q<jruby-openssl>, [">= 0"])
      s.add_development_dependency(%q<activerecord-jdbcsqlite3-adapter>, [">= 0"])
      s.add_development_dependency(%q<spree>, ["= 0.70.3"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
    else
      s.add_dependency(%q<rails>, ["= 3.1.3"])
      s.add_dependency(%q<activerecord>, ["= 3.1.3"])
      s.add_dependency(%q<activesupport>, ["= 3.1.3"])
      s.add_dependency(%q<jruby-openssl>, [">= 0"])
      s.add_dependency(%q<activerecord-jdbcsqlite3-adapter>, [">= 0"])
      s.add_dependency(%q<spree>, ["= 0.70.3"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.1.3"])
    s.add_dependency(%q<activerecord>, ["= 3.1.3"])
    s.add_dependency(%q<activesupport>, ["= 3.1.3"])
    s.add_dependency(%q<jruby-openssl>, [">= 0"])
    s.add_dependency(%q<activerecord-jdbcsqlite3-adapter>, [">= 0"])
    s.add_dependency(%q<spree>, ["= 0.70.3"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
  end
end

