source 'https://rubygems.org'


# DEFINE WHICH VERSIONS ON VITAL GEMS WE WANT TO TEST WITH

gem 'rails', '4.1.8'

gem 'spreadsheet', '1.0.0'
gem 'paperclip'
gem 'activesupport'

gem 'database_cleaner'

gem 'factory_girl_rails'

gem 'rspec'
gem 'rspec-core'
gem 'rspec-expectations' # RSpec matchers for should and should_not.
gem 'rspec-mocks'        # RSpec test double framework with stubbing and mocking.
gem 'rspec-rails'       # RSpec version 2.x for Rails version 3.x.

# we need both, for JRuby testing of Excel and non JRuby csv
platform :jruby do
  gem 'jruby-openssl'
  gem 'activerecord-jdbcsqlite3-adapter'
end

platform :ruby do
  gem 'sqlite3'
end

